import type {
  AccountPrefs,
  Activity,
  AppState,
  Comment,
  Issue,
  Notification,
  Project,
  Sprint,
  User,
  Workspace,
} from '@/lib/types'

const defaultColumns = [
  { id: 'todo', title: 'To Do' },
  { id: 'in-progress', title: 'In Progress' },
  { id: 'in-review', title: 'In Review' },
  { id: 'done', title: 'Done' },
]

const defaultPrefs: AccountPrefs = {
  notifyAssigned: true,
  notifyComments: true,
  notifyStatus: true,
}

export const users: User[] = [
  {
    id: 'amelia',
    name: 'Amelia Chen',
    email: 'amelia@flowboard.io',
    initials: 'AC',
    color: 'bg-primary/20 text-foreground',
  },
  {
    id: 'marcus',
    name: 'Marcus Reid',
    email: 'marcus@flowboard.io',
    initials: 'MR',
    color: 'bg-chart-2/15 text-chart-2',
  },
  {
    id: 'priya',
    name: 'Priya Nair',
    email: 'priya@flowboard.io',
    initials: 'PN',
    color: 'bg-chart-4/15 text-chart-4',
  },
  {
    id: 'jonas',
    name: 'Jonas Vik',
    email: 'jonas@flowboard.io',
    initials: 'JV',
    color: 'bg-chart-5/15 text-chart-5',
  },
  {
    id: 'sofia',
    name: 'Sofia Ruiz',
    email: 'sofia@flowboard.io',
    initials: 'SR',
    color: 'bg-chart-3/20 text-chart-3',
  },
  {
    id: 'logan',
    name: 'Logan Park',
    email: 'logan@flowboard.io',
    initials: 'LP',
    color: 'bg-muted text-muted-foreground',
  },
]

const workspace: Workspace = {
  id: 'ws-flowboard',
  name: 'Flowboard',
  members: [
    { userId: 'amelia', role: 'owner' },
    { userId: 'marcus', role: 'admin' },
    { userId: 'priya', role: 'member' },
    { userId: 'jonas', role: 'member' },
    { userId: 'sofia', role: 'member' },
    { userId: 'logan', role: 'guest' },
  ],
}

const projects: Project[] = [
  {
    id: 'mw',
    key: 'MW',
    name: 'Mobile Web',
    description: 'Responsive web app for on-the-go project tracking and reviews.',
    labels: ['Design', 'Backend', 'Frontend', 'Platform', 'API', 'Content', 'DevOps', 'QA'],
    columns: defaultColumns,
    members: [
      { userId: 'amelia', role: 'owner' },
      { userId: 'marcus', role: 'admin' },
      { userId: 'priya', role: 'member' },
      { userId: 'jonas', role: 'member' },
      { userId: 'sofia', role: 'member' },
      { userId: 'logan', role: 'guest' },
    ],
  },
  {
    id: 'api',
    key: 'API',
    name: 'Platform API',
    description: 'Public and internal APIs, auth session service, and pagination contracts.',
    labels: ['API', 'Backend', 'Platform', 'DevOps'],
    columns: defaultColumns,
    members: [
      { userId: 'amelia', role: 'owner' },
      { userId: 'marcus', role: 'admin' },
      { userId: 'jonas', role: 'member' },
    ],
  },
  {
    id: 'ds',
    key: 'DS',
    name: 'Design System',
    description: 'Tokens, components, and documentation for the Flowboard UI kit.',
    labels: ['Design', 'Frontend', 'Content'],
    columns: defaultColumns,
    members: [
      { userId: 'amelia', role: 'owner' },
      { userId: 'sofia', role: 'member' },
      { userId: 'priya', role: 'member' },
    ],
  },
]

const sprints: Sprint[] = [
  {
    id: 'mw-s23',
    projectId: 'mw',
    name: 'Sprint 23',
    status: 'closed',
    startDate: '2026-08-11',
    endDate: '2026-08-24',
  },
  {
    id: 'mw-s24',
    projectId: 'mw',
    name: 'Sprint 24',
    status: 'active',
    startDate: '2026-08-25',
    endDate: '2026-09-07',
  },
  {
    id: 'mw-s25',
    projectId: 'mw',
    name: 'Sprint 25',
    status: 'planned',
    startDate: '2026-09-08',
    endDate: '2026-09-21',
  },
  {
    id: 'api-s8',
    projectId: 'api',
    name: 'Sprint 8',
    status: 'active',
    startDate: '2026-08-25',
    endDate: '2026-09-07',
  },
  {
    id: 'ds-s4',
    projectId: 'ds',
    name: 'Sprint 4',
    status: 'active',
    startDate: '2026-08-25',
    endDate: '2026-09-07',
  },
]

const issues: Issue[] = [
  {
    id: 'MW-128',
    projectId: 'mw',
    title: 'Design new onboarding flow for mobile users',
    description:
      'Map the first-run experience for phones: welcome, workspace join, and first board. Include empty states and a skip path for invited guests.',
    priority: 'high',
    type: 'feature',
    column: 'todo',
    tag: 'Design',
    assigneeId: 'amelia',
    dueDate: '2026-09-05',
    sprintId: 'mw-s24',
    blockedBy: [],
    subtasks: [
      { id: 'st-1', title: 'Wireframe 3 screens', done: true },
      { id: 'st-2', title: 'Critique with Sofia', done: false },
      { id: 'st-3', title: 'Hand off tokens', done: false },
    ],
    attachments: [
      { id: 'att-1', name: 'onboarding-flow.fig', size: '2.4 MB' },
      { id: 'att-2', name: 'mobile-breakpoints.pdf', size: '180 KB' },
    ],
    createdAt: '2026-08-26T09:12:00.000Z',
    updatedAt: '2026-09-01T14:20:00.000Z',
  },
  {
    id: 'MW-131',
    projectId: 'mw',
    title: 'Investigate slow query on the analytics dashboard',
    description:
      'Dashboard cards take 4–6s on staging. Profile the issues aggregation and check missing indexes on project_id + updated_at.',
    priority: 'high',
    type: 'bug',
    column: 'todo',
    tag: 'Backend',
    assigneeId: 'marcus',
    dueDate: '2026-08-30',
    sprintId: 'mw-s24',
    blockedBy: [],
    subtasks: [{ id: 'st-4', title: 'Capture EXPLAIN ANALYZE', done: true }],
    attachments: [{ id: 'att-3', name: 'slow-query.log', size: '64 KB' }],
    createdAt: '2026-08-27T11:00:00.000Z',
    updatedAt: '2026-08-31T16:40:00.000Z',
  },
  {
    id: 'MW-134',
    projectId: 'mw',
    title: 'Add empty states to the reports section',
    description: 'When a project has no completed issues this week, show a calm empty state instead of a blank chart.',
    priority: 'low',
    type: 'improvement',
    column: 'todo',
    tag: 'Frontend',
    assigneeId: 'priya',
    dueDate: null,
    sprintId: null,
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-28T08:30:00.000Z',
    updatedAt: '2026-08-28T08:30:00.000Z',
  },
  {
    id: 'MW-119',
    projectId: 'mw',
    title: 'Build reusable data table component with sorting',
    description: 'Shared table for the issues list: sticky header, sort by priority/status, and compact density on mobile.',
    priority: 'medium',
    type: 'feature',
    column: 'in-progress',
    tag: 'Frontend',
    assigneeId: 'jonas',
    dueDate: '2026-09-04',
    sprintId: 'mw-s24',
    blockedBy: [],
    subtasks: [
      { id: 'st-5', title: 'Column API', done: true },
      { id: 'st-6', title: 'Keyboard sort', done: false },
    ],
    attachments: [],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-09-02T09:10:00.000Z',
  },
  {
    id: 'MW-122',
    projectId: 'mw',
    title: 'Migrate authentication to the new session service',
    description: 'Swap cookie session helper for the platform session service. Keep mock login working in this demo.',
    priority: 'high',
    type: 'task',
    column: 'in-progress',
    tag: 'Platform',
    assigneeId: 'sofia',
    dueDate: '2026-09-08',
    sprintId: 'mw-s24',
    blockedBy: ['API-18'],
    subtasks: [],
    attachments: [{ id: 'att-4', name: 'session-migration.md', size: '12 KB' }],
    createdAt: '2026-08-21T13:15:00.000Z',
    updatedAt: '2026-09-01T11:00:00.000Z',
  },
  {
    id: 'MW-140',
    projectId: 'mw',
    title: 'Fix avatar cropping on Safari',
    description: 'Circular avatars clip initials on Safari 18 when ring-2 is applied. Repro on the board cards.',
    priority: 'low',
    type: 'bug',
    column: 'in-progress',
    tag: 'Frontend',
    assigneeId: 'amelia',
    dueDate: null,
    sprintId: 'mw-s24',
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-29T15:00:00.000Z',
    updatedAt: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 'MW-112',
    projectId: 'mw',
    title: 'Review API pagination contract with the backend team',
    description: 'Align cursor vs offset for the issues endpoint before the table ships.',
    priority: 'medium',
    type: 'task',
    column: 'in-review',
    tag: 'API',
    assigneeId: 'marcus',
    dueDate: '2026-09-03',
    sprintId: 'mw-s24',
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-18T09:00:00.000Z',
    updatedAt: '2026-09-01T17:30:00.000Z',
  },
  {
    id: 'MW-115',
    projectId: 'mw',
    title: 'Update billing page copy and pricing tiers',
    description: 'Rewrite Free / Team / Scale blurbs. No payment integration in this mock.',
    priority: 'medium',
    type: 'improvement',
    column: 'in-review',
    tag: 'Content',
    assigneeId: 'priya',
    dueDate: null,
    sprintId: 'mw-s24',
    blockedBy: [],
    subtasks: [],
    attachments: [{ id: 'att-5', name: 'pricing-draft.docx', size: '88 KB' }],
    createdAt: '2026-08-19T12:00:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z',
  },
  {
    id: 'MW-101',
    projectId: 'mw',
    title: 'Set up CI pipeline for preview deployments',
    description: 'Preview deploys on every pull request with the design-token smoke check.',
    priority: 'high',
    type: 'task',
    column: 'done',
    tag: 'DevOps',
    assigneeId: 'jonas',
    dueDate: '2026-08-20',
    sprintId: 'mw-s23',
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-12T08:00:00.000Z',
    updatedAt: '2026-08-20T16:00:00.000Z',
  },
  {
    id: 'MW-104',
    projectId: 'mw',
    title: 'Implement dark mode tokens across the design system',
    description: 'Derive dark surfaces from Neutral. Not enabled in the app yet — tokens only.',
    priority: 'medium',
    type: 'feature',
    column: 'done',
    tag: 'Design',
    assigneeId: 'sofia',
    dueDate: '2026-08-22',
    sprintId: 'mw-s23',
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-13T10:00:00.000Z',
    updatedAt: '2026-09-01T12:00:00.000Z',
  },
  {
    id: 'MW-108',
    projectId: 'mw',
    title: 'Write end-to-end tests for the checkout flow',
    description: 'Playwright coverage for guest vs member checkout. Skipped in this mock app.',
    priority: 'low',
    type: 'task',
    column: 'done',
    tag: 'QA',
    assigneeId: 'amelia',
    dueDate: '2026-08-24',
    sprintId: 'mw-s23',
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-14T11:20:00.000Z',
    updatedAt: '2026-08-24T15:10:00.000Z',
  },
  {
    id: 'API-18',
    projectId: 'api',
    title: 'Ship session service v2',
    description: 'Token rotation and workspace-scoped sessions for the new auth path.',
    priority: 'high',
    type: 'feature',
    column: 'in-progress',
    tag: 'Platform',
    assigneeId: 'marcus',
    dueDate: '2026-09-06',
    sprintId: 'api-s8',
    blockedBy: [],
    subtasks: [{ id: 'st-7', title: 'Rotation spec', done: true }],
    attachments: [],
    createdAt: '2026-08-22T09:00:00.000Z',
    updatedAt: '2026-09-02T08:00:00.000Z',
  },
  {
    id: 'API-21',
    projectId: 'api',
    title: 'Cursor pagination for issues list',
    description: 'Replace offset pagination. Return next_cursor and has_more.',
    priority: 'medium',
    type: 'task',
    column: 'todo',
    tag: 'API',
    assigneeId: 'jonas',
    dueDate: '2026-09-10',
    sprintId: 'api-s8',
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-28T14:00:00.000Z',
    updatedAt: '2026-08-28T14:00:00.000Z',
  },
  {
    id: 'API-09',
    projectId: 'api',
    title: 'Rate limit login attempts',
    description: 'Mock only — document the intended 10/min/IP policy.',
    priority: 'high',
    type: 'bug',
    column: 'in-review',
    tag: 'Backend',
    assigneeId: 'marcus',
    dueDate: '2026-09-02',
    sprintId: 'api-s8',
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-16T09:00:00.000Z',
    updatedAt: '2026-09-01T18:00:00.000Z',
  },
  {
    id: 'API-04',
    projectId: 'api',
    title: 'Health check endpoint',
    description: 'GET /health returns version and dependency pings.',
    priority: 'low',
    type: 'task',
    column: 'done',
    tag: 'DevOps',
    assigneeId: 'jonas',
    dueDate: '2026-08-18',
    sprintId: 'api-s8',
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-10T09:00:00.000Z',
    updatedAt: '2026-08-18T11:00:00.000Z',
  },
  {
    id: 'DS-12',
    projectId: 'ds',
    title: 'Document sidebar navigation patterns',
    description: 'Active states, workspace switcher, and collapsed mobile overlay.',
    priority: 'medium',
    type: 'task',
    column: 'in-progress',
    tag: 'Content',
    assigneeId: 'sofia',
    dueDate: '2026-09-04',
    sprintId: 'ds-s4',
    blockedBy: [],
    subtasks: [],
    attachments: [{ id: 'att-6', name: 'nav-spec.png', size: '420 KB' }],
    createdAt: '2026-08-25T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'DS-08',
    projectId: 'ds',
    title: 'Add empty-state illustration guidelines',
    description: 'One-color marks using Primary wash. No new brand colors.',
    priority: 'low',
    type: 'improvement',
    column: 'todo',
    tag: 'Design',
    assigneeId: 'priya',
    dueDate: null,
    sprintId: null,
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-26T11:00:00.000Z',
    updatedAt: '2026-08-26T11:00:00.000Z',
  },
  {
    id: 'DS-03',
    projectId: 'ds',
    title: 'Publish button variants',
    description: 'Default, outline, ghost, destructive — already in the kit.',
    priority: 'medium',
    type: 'feature',
    column: 'done',
    tag: 'Frontend',
    assigneeId: 'sofia',
    dueDate: '2026-08-28',
    sprintId: 'ds-s4',
    blockedBy: [],
    subtasks: [],
    attachments: [],
    createdAt: '2026-08-15T09:00:00.000Z',
    updatedAt: '2026-08-28T16:00:00.000Z',
  },
]

const comments: Comment[] = [
  {
    id: 'c-1',
    issueId: 'MW-128',
    authorId: 'sofia',
    body: 'Can we reuse the existing welcome illustration instead of a new one?',
    createdAt: '2026-08-30T13:10:00.000Z',
  },
  {
    id: 'c-2',
    issueId: 'MW-128',
    authorId: 'amelia',
    body: 'Yes — tint it with the primary wash. I will attach the frame today.',
    createdAt: '2026-08-30T14:02:00.000Z',
  },
  {
    id: 'c-3',
    issueId: 'MW-131',
    authorId: 'jonas',
    body: 'I can add a covering index this afternoon if you send the query shape.',
    createdAt: '2026-08-31T09:40:00.000Z',
  },
  {
    id: 'c-4',
    issueId: 'MW-119',
    authorId: 'priya',
    body: 'Please keep the header height at h-9 so it lines up with the toolbar.',
    createdAt: '2026-09-01T11:22:00.000Z',
  },
  {
    id: 'c-5',
    issueId: 'API-18',
    authorId: 'amelia',
    body: 'MW-122 is blocked on this — any chance it lands before Thursday?',
    createdAt: '2026-09-01T15:00:00.000Z',
  },
]

const activities: Activity[] = [
  {
    id: 'a-1',
    issueId: 'MW-128',
    actorId: 'amelia',
    type: 'created',
    message: 'created this issue',
    createdAt: '2026-08-26T09:12:00.000Z',
  },
  {
    id: 'a-2',
    issueId: 'MW-128',
    actorId: 'sofia',
    type: 'comment',
    message: 'commented',
    createdAt: '2026-08-30T13:10:00.000Z',
  },
  {
    id: 'a-3',
    issueId: 'MW-131',
    actorId: 'marcus',
    type: 'created',
    message: 'created this issue',
    createdAt: '2026-08-27T11:00:00.000Z',
  },
  {
    id: 'a-4',
    issueId: 'MW-119',
    actorId: 'jonas',
    type: 'status',
    message: 'moved this to In Progress',
    createdAt: '2026-08-29T10:00:00.000Z',
  },
  {
    id: 'a-5',
    issueId: 'MW-104',
    actorId: 'sofia',
    type: 'status',
    message: 'moved this to Done',
    createdAt: '2026-09-01T12:00:00.000Z',
  },
  {
    id: 'a-6',
    issueId: 'MW-112',
    actorId: 'marcus',
    type: 'status',
    message: 'moved this to In Review',
    createdAt: '2026-09-01T17:30:00.000Z',
  },
  {
    id: 'a-7',
    issueId: 'MW-140',
    actorId: 'priya',
    type: 'assignee',
    message: 'assigned Amelia Chen',
    createdAt: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 'a-8',
    issueId: 'API-18',
    actorId: 'marcus',
    type: 'updated',
    message: 'updated the description',
    createdAt: '2026-09-02T08:00:00.000Z',
  },
  {
    id: 'a-9',
    issueId: 'DS-03',
    actorId: 'sofia',
    type: 'status',
    message: 'moved this to Done',
    createdAt: '2026-08-28T16:00:00.000Z',
  },
]

const notifications: Notification[] = [
  {
    id: 'n-1',
    userId: 'amelia',
    type: 'comment',
    issueId: 'MW-128',
    message: 'Sofia Ruiz commented on MW-128',
    read: false,
    createdAt: '2026-08-30T13:10:00.000Z',
  },
  {
    id: 'n-2',
    userId: 'amelia',
    type: 'assigned',
    issueId: 'MW-140',
    message: 'You were assigned MW-140',
    read: false,
    createdAt: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 'n-3',
    userId: 'amelia',
    type: 'status_change',
    issueId: 'MW-104',
    message: 'MW-104 was moved to Done',
    read: true,
    createdAt: '2026-09-01T12:00:00.000Z',
  },
  {
    id: 'n-4',
    userId: 'marcus',
    type: 'comment',
    issueId: 'MW-131',
    message: 'Jonas Vik commented on MW-131',
    read: false,
    createdAt: '2026-08-31T09:40:00.000Z',
  },
  {
    id: 'n-5',
    userId: 'jonas',
    type: 'assigned',
    issueId: 'MW-119',
    message: 'You were assigned MW-119',
    read: true,
    createdAt: '2026-08-20T10:05:00.000Z',
  },
]

const STORAGE_VERSION = 1

export function createInitialState(): AppState {
  const prefs: Record<string, AccountPrefs> = {}
  for (const user of users) {
    prefs[user.id] = { ...defaultPrefs }
  }

  return {
    version: STORAGE_VERSION,
    workspace: structuredClone(workspace),
    users: structuredClone(users),
    projects: structuredClone(projects),
    issues: structuredClone(issues),
    comments: structuredClone(comments),
    activities: structuredClone(activities),
    sprints: structuredClone(sprints),
    notifications: structuredClone(notifications),
    currentUserId: null,
    currentProjectId: 'mw',
    accountPrefs: prefs,
    composer: { open: false, columnId: null },
  }
}

export { STORAGE_VERSION, defaultColumns, defaultPrefs }
